version: '3.8'
services:
  postgres:
    image: postgres:13.1
    container_name: ${PROJECT_NAME:-to-do-list}-postgres
    ports:
      - "${POSTGRES_PORT:-9186}:5432"
    volumes:
      - to_do_list_postgres_data:/var/lib/postgresql/data
    networks:
      - to-do-list-api-network
    restart: always
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PROJECT_NAME:-to-do-list}-pgadmin
    ports:
      - "${PGADMIN_PORT:-9187}:80"
    networks:
      - to-do-list-api-network
    restart: always
    env_file:
      - docker.env

    
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    container_name: ${PROJECT_NAME:-to-do-list}-php
    volumes:
      - '.:/usr/src/app'
    user: ${LOCAL_USER}
    networks:
      - to-do-list-api-network
    env_file:
      - docker.env
    
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    container_name: ${PROJECT_NAME:-to-do-list}-nginx
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT:-9185}:80'
    depends_on:
         - php
    networks:
      - to-do-list-api-network
    env_file:
      - docker.env


networks:
  to-do-list-api-network: { }

volumes:
  to_do_list_postgres_data: